/*** Generated by streamline 0.10.12 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Bottleneck, a, asyncReplace, contentTypes, crypto, getHash, isAltered, rDomains, rLookbehind, redirectAllURLs, redirectToHash, sendCuratedData, settings, url;

  crypto = require("crypto");

  url = require("url");

  asyncReplace = require("async-replace");

  settings = require("../settings");

  Bottleneck = require("bottleneck");

  getHash = function getHash__1(redisClient, host, clientIP, _) { var hash, keys, savedHashKey, values; var __frame = { name: "getHash__1", line: 14 }; return __func(_, this, arguments, getHash__1, 3, __frame, function __$getHash__1() {

      savedHashKey = ((("hash-" + clientIP) + "-") + host);
      return redisClient.get(savedHashKey, __cb(_, __frame, 3, 23, function ___(__0, __2) { hash = __2; return (function __$getHash__1(__then) {
          if ((hash == null)) {
            return (crypto.pseudoRandomBytes(16, __cb(_, __frame, 5, 21, function ___(__0, __3) { hash = __3.toString("hex");
              keys = [("hostTunneling-" + hash),("xforwardedfor-" + hash),savedHashKey,];
              values = [host,clientIP,hash,];
              return keys.forEach_(__cb(_, __frame, 8, 11, __then, true), -1, function __1(_, k, i) { var __frame = { name: "__1", line: 22 }; return __func(_, this, arguments, __1, 0, __frame, function __$__1() {
                  return redisClient.set([k,values[i],], __cb(_, __frame, 1, 20, function __$__1() {
                    return redisClient.expire([k,settings.hostTunnelingCaching,], __cb(_, __frame, 2, 27, _, true)); }, true)); }); }); }, true))); } else { __then(); } ; })(function __$getHash__1() {


          return _(null, hash); }); }, true)); }); };


  redirectToHash = function(res, hash, path) {
    var redirect;
    redirect = (((("https://" + hash) + ".") + settings.hostTunnelingDomain) + path);
    res.writeHead(302, {
      Location: redirect });

    return res.end((((("<html><body>The unblock.us.org project<br /><br />Unblocked at <a href=\"" + redirect) + "\">") + redirect) + "</a></body></html>")); };


  contentTypes = {
  "application/javascript": "application/javascript",
  "application/xhtml+xml": "application/xhtml+xml",
  "application/xml": "application/xml",
  "image/svg+xml": "image/svg+xml",
  "text/css": "text/css",
  "text/html": "text/html",
  "text/javascript": "text/javascript" };


  isAltered = function(ct) {
    return (contentTypes[ct] != null); };


  rDomains = new RegExp((("(.|^)(?:https://)?(?:(?:[a-zA-Z0-9-]+[.]{1})*?)?(?:" + ((function() {
    var _results;
    _results = [];
    for (a in settings.hijacked) {
      _results.push((("(?:" + a.replace(/[.]/g, "[.]")) + ")")); };

    return _results;
  })()).join("|")) + ")"), "g");

  rLookbehind = new RegExp("^[^a-zA-Z0-9-.]?$");

  redirectAllURLs = function redirectAllURLs__2(str, redisClient, limiter, clientIP, _) { var __frame = { name: "redirectAllURLs__2", line: 64 }; return __func(_, this, arguments, redirectAllURLs__2, 4, __frame, function __$redirectAllURLs__2() { return (function __$redirectAllURLs__2(__then) {
        if (Array.isArray(str)) {
          return str.map_(__cb(_, __frame, 2, 17, _, true), -1, function __1(_, s) { var __frame = { name: "__1", line: 66 }; return __func(_, this, arguments, __1, 0, __frame, function __$__1() {
              return redirectAllURLs(s, redisClient, limiter, clientIP, __cb(_, __frame, 1, 15, _, true)); }); }); } else { __then(); } ; })(function __$redirectAllURLs__2() {


        return asyncReplace(str, rDomains, (function __2(found, lookbehind, position, text, _) { var formatted, hash, parsed; var __frame = { name: "__2", line: 70 }; return __func(_, this, arguments, __2, 4, __frame, function __$__2() {

            if (!rLookbehind.test(lookbehind)) {
              return _(null, found); } ;

            if ((lookbehind.length > 0)) {
              found = found.slice(1); } ;

            parsed = url.parse(found);
            parsed.path = "";
            parsed.pathname = "";
            if ((((parsed.host == null)) || ((parsed.hostname == null)))) {
              parsed.hostname = parsed.href; } ;

            parsed.host = null;
            if ((parsed.protocol != null)) {
              parsed.protocol = "https"; } ;

            return limiter.submit(getHash, redisClient, parsed.hostname, clientIP, __cb(_, __frame, 18, 21, function ___(__0, __1) { hash = __1;
              parsed.hostname = ((hash + ".") + settings.hostTunnelingDomain);
              formatted = url.format(parsed);
              if ((formatted.slice(0, 2) === "//")) {
                return _(null, (lookbehind + formatted.slice(2))); }
               else {
                return _(null, (lookbehind + formatted)); } ; _(); }, true)); }); }), __cb(_, __frame, 6, 11, _, true)); }); }); };




  sendCuratedData = function sendCuratedData__3(res, pres, redisClient, limiter, clientIP, _) { var altered, buffers, _ref; var __frame = { name: "sendCuratedData__3", line: 99 }; return __func(_, this, arguments, sendCuratedData__3, 5, __frame, function __$sendCuratedData__3() {

      return ["access-control-allow-origin","set-cookie",].forEach_(__cb(_, __frame, 2, 50, function __$sendCuratedData__3() {





        res.writeHead(pres.statusCode, pres.headers);
        altered = isAltered((((_ref = pres.headers["content-type"]) != null) ? _ref.toLowerCase().split(";")[0].trim() : void 0));
        if (altered) {
          buffers = [];
          pres.on("data", function(data) {
            return buffers.push(data); });

          return _(null, pres.on("end", function() {
            return redirectAllURLs((new Buffer(Buffer.concat(buffers))).toString("utf8"), redisClient, limiter, clientIP, function(err, curatedPage) {
              if ((err != null)) {
                throw err; } ;

              return res.end(curatedPage, "utf8"); }); })); }


         else {
          pres.on("data", function(data) {
            return res.write(data); });

          return _(null, pres.on("end", function() {
            return res.end(); })); } ; _(); }, true), -1, function __1(_, header) { var _ref; var __frame = { name: "__1", line: 101 }; return __func(_, this, arguments, __1, 0, __frame, function __$__1() { return (function __$__1(__then) { if ((((((_ref = pres.headers[header]) != null) ? _ref.length : void 0)) > 0)) { return redirectAllURLs(pres.headers[header], redisClient, limiter, clientIP, __cb(_, __frame, 3, 38, function ___(__0, __2) { var __1 = pres.headers[header] = __2; return _(null, __1); }, true)); } else { __then(); } ; })(_); }); }); }); };




  module.exports = {
    getHash: getHash,
    redirectToHash: redirectToHash,
    redirectAllURLs: redirectAllURLs,
    sendCuratedData: sendCuratedData };


}).call(this);
